_core:
  default_config_hash: _UaIWu0_ZD3lUs97wlFC2Koi-o7Bex69Xr9q36nJtkY
langcode: en
enable_globally: 1
enable_globally_on_admin_routes: false
default_challenge: recaptcha/reCAPTCHA
description: ''
title: CAPTCHA
administration_mode: false
administration_mode_on_admin_routes: false
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
default_validation: 1
persistence: 1
enable_stats: true
log_wrong_responses: true
