_core:
  default_config_hash: 2VIFfYIzLIphEpkJSH9KfhEE0P66ieHfusDj6QMJIzY
selectors: ".node\r\n.container\r\n.field--name-field-media-oembed-video\r\n#block-telliodora-content\r\narticle"
custom_vendors: ''
ignore_selectors: ''
